### ISSUE TITLE
MX server wuldn't be domain name

### ISSUE THREAD

**Issue by arius** [lantins/dns-zone#6]
Hi, i have problem with loading MX records, where server si not domain name, but just "mail".
For example:
```
                        MX      10 mail               
mail                    A       some_ip
```
 
It's valid record, but you don't load it because you expect full domain name like mail.example.com.

**Comment by lantins** [comment]
Can you post the full zone?

**Comment by arius** [comment]
```
$TTL 2m
@               1d      SOA     ns.eurosignal.cz. hostmaster.eurosignal.cz. 2012101011 1d 1h 4w 10m
                        NS      ns1.eurosignal.cz.
                        NS      ns2.eurosignal.cz.
                        NS      ns3.eurosignal.cz.

                        MX      10 mail               

mail                    A       77.240.96.38
                        AAAA    2a00:1aa8:1::38
www                     A       77.240.96.37
                        AAAA    2a00:1aa8:1::37
```

**Comment by lantins** [comment]
You will need to define a `$ORIGIN` directive at the top of your zone file.

Now, bind will handle zone without an `$ORIGIN` directive, the origin is inferred by the `zone "<zone-name>" {}` clause.

I suggest your zones have this directive to be more portable.

However! I can see this being a pain in the arse, we need a way to load a zone and pass it a origin.

How about this:

```ruby
zone = DNS::Zone.load(zone_as_string, 'example.origin.com')
```

Where the second param is optional, and any ORIGIN defined _within_ the zone will ultimately win?

It is possible for a zone to use multiple ORIGIN directives, the lib does not handle things like that, yet, pull request anyone? :)

**Comment by mrideout** [comment]
I'm not the OP, but adding a param that allows you to specify a default ORIGIN that would be overwritten by an ORIGIN within the zone would be useful to me.

**Comment by arius** [comment]
You can add the second paramets for specify origin, but it doesn't solved my problem. Because when i added $ORIGIN to zone file, i still dind't get the MX record. 

```
$TTL 2m
$ORIGIN kalle.cz
@		1d	SOA	ns.eurosignal.cz. hostmaster.eurosignal.cz. 2012102410 1d 1h 4w 10m
			NS	a.ns.eurosignal.cz.
			NS	b.ns.eurosignal.cz.
			NS	c.ns.eurosignal.cz.
			MX	10 mail

mail			A	77.240.96.38
			AAAA	2a00:1aa8:1::38

www			A	82.208.35.155

```

```
pp zone
#<DNS::Zone:0x007ff53b27b2c0
 @origin="kalle.cz",
 @records=
  [#<DNS::Zone::RR::SOA:0x007ff53b27ac08
    @email="hostmaster.eurosignal.cz.",
    @expiry_ttl="4w",
    @klass="IN",
    @label="@",
    @minimum_ttl="10m",
    @nameserver="ns.eurosignal.cz.",
    @refresh_ttl="1d",
    @retry_ttl="1h",
    @serial=2012102410,
    @ttl="1d">,
   #<DNS::Zone::RR::NS:0x007ff53b385a08
    @klass="IN",
    @label="\t",
    @nameserver="a.ns.eurosignal.cz.",
    @ttl=nil>,
   #<DNS::Zone::RR::NS:0x007ff53b385580
    @klass="IN",
    @label="\t",
    @nameserver="b.ns.eurosignal.cz.",
    @ttl=nil>,
   #<DNS::Zone::RR::NS:0x007ff53b385288
    @klass="IN",
    @label="\t",
    @nameserver="c.ns.eurosignal.cz.",
    @ttl=nil>,
   #<DNS::Zone::RR::A:0x007ff53b384900
    @address="77.240.96.38",
    @klass="IN",
    @label="mail",
    @ttl=nil>,
   #<DNS::Zone::RR::AAAA:0x007ff53b3841d0
    @address="2a00:1aa8:1::38",
    @klass="IN",
    @label="\t",
    @ttl=nil>,
   #<DNS::Zone::RR::A:0x007ff53b383d20
    @address="82.208.35.155",
    @klass="IN",
    @label="www",
    @ttl=nil>,
   #<DNS::Zone::RR::A:0x007ff53b383a00
    @address="188.95.122.146",
    @klass="IN",
    @label="brana",
    @ttl=nil>],
 @ttl="2m">
```

**Comment by lantins** [comment]
@mrideout I've opened another issue to address that: #7

@arius Couple of things:

1) You should add a . (dot) at the end of your ORIGIN domain-name (e.g. `$ORIGIN kalle.cz.`)
2) You are correct, even with a ORIGIN the code still doesn't work correctly, your use of a unqualified domain-name is _valid_.

**Comment by lantins** [comment]
@arius Can you give it a try using the `master` branch?

**Comment by arius** [comment]
OK it does work for me even without origin directive. Thank you
